<%--
  Created by IntelliJ IDEA.
  User: Kylian
  Date: 2023/7/5
  Time: 23:47
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Login Page</title>
</head>
<body>
    <!-- Get loginFailed attribute which is generated by server when inputted name or password is wrong -->
    <%! boolean loginFailed; %>
    <%
        loginFailed = "true".equals(request.getParameter("loginFailed"));
    %>

    <script>
        const checkForm = () => {
            const username = document.getElementById("username").value;
            const password = document.getElementById("password").value;

            if (username.length < 3) {
                // Username is shorter than 3.
                document.getElementById("notification").innerHTML = "Username cannot be shorter than 3 characters.";
                return false;
            }
            if (username.length > 20) {
                // Username is longer than 20.
                document.getElementById("notification").innerHTML = "Username cannot be longer than 20 characters.";
                return false;
            }
            if (password.length < 6) {
                // Password is shorter than 6.
                document.getElementById("notification").innerHTML = "Password cannot be shorter than 6 characters.";
                return false;
            }
            if (password.length > 20) {
                // Password is longer than 20.
                document.getElementById("notification").innerHTML = "Password cannot be longer than 20 characters.";
                return false;
            }

            // Input is legal, send to server.
            document.getElementById("loginForm").submit();
        }
    </script>
    <h1>Log In</h1>

    <!-- Login form -->
    <form action="login_service" method="post" id="loginForm">
        <label>
            Username:
            <input type="text" name="username" id="username">
        </label>
        <br>
        <label>
            Password:
            <input type="password" name="password" id="password">
        </label>
        <br>
        <input type="button" value="LOGIN" onclick="checkForm()">
    </form>

    <!-- Show notification if login failed -->
    <p id="notification"><%= loginFailed ? "Log in failed! Please check your username and password!" : "" %></p>
    <a href="index.jsp">Back to home</a>
</body>
</html>
