<%--
  Created by IntelliJ IDEA.
  User: Kylian
  Date: 2023/7/5
  Time: 22:12
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Register Page</title>
</head>
<body>
    <!-- Get nameExists attribute which is generated by server when inputted name is already exists -->
    <%! boolean nameExists; %>
    <%
        nameExists = "true".equals(request.getParameter("nameExists"));
    %>

    <script>
        const checkForm = () => {
            const username = document.getElementById("username").value;
            const password = document.getElementById("password").value;
            const repeatPassword = document.getElementById("repeatPassword").value;

            if (username.length < 3) {
                document.getElementById("notification").innerHTML = "Username cannot be shorter than 3 characters.";
                return false;
            }
            if (username.length > 20) {
                document.getElementById("notification").innerHTML = "Username cannot be longer than 20 characters.";
                return false;
            }
            if (password.length < 6) {
                document.getElementById("notification").innerHTML = "Password cannot be shorter than 6 characters.";
                return false;
            }
            if (password.length > 20) {
                document.getElementById("notification").innerHTML = "Password cannot be longer than 20 characters.";
                return false;
            }
            if (password !== repeatPassword) {
                document.getElementById("notification").innerHTML = "Password and repetition must be the same.";
                return false;
            }

            document.getElementById("registerForm").submit();
        }
    </script>
    <h1>Create an account</h1>

    <!-- Register form -->
    <form action="register_service" method="post" id="registerForm">
        <label>
            Username:
            <input type="text" name="username" id="username">
        </label>
        <br>
        <label>
            Password:
            <input type="password" name="password" id="password">
        </label>
        <br>
        <label>
            Repeat your Password:
            <input type="password" id="repeatPassword">
        </label>
        <br>
        <input type="button" value="REGISTER" onclick="checkForm()">
    </form>

    <!-- Show notification if username is already exists -->
    <p id="notification"><%= nameExists ? "Username is already exists! Please change your username." : "" %></p>
    <a href="index.jsp">Back to home</a>
</body>
</html>
